"""Generation tools on the platform's Agent API.

Two of them, and the pair is the point.

``generate_image`` spends money and is declared a ``WRITE``, because the guard's
job is to gate irreversible actions and a rouble spent is not coming back. It is
not enough to call it a read merely because nothing in a database changed.

``estimate_generation`` is free and works for **every** media type, video
included. There is deliberately no video generation tool: a clip costs 149-590 RUB,
and the difference between "the agent can price it" and "the agent can spend it"
is one accidental tool call. Pricing is exposed; spending is not.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, JsonValue

from conduit.adapters.vibemarketolog.client import GenerationError, VibemarketologClient
from conduit.core.tools import (
    SideEffect,
    ToolContext,
    ToolErrorCode,
    ToolRegistry,
    ToolResult,
    ToolSpec,
)

__all__ = ["NAMESPACE", "EstimateParams", "GenerateImageParams", "register"]

NAMESPACE = "vibemarketolog"

ASPECT_RATIOS = Literal["1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9"]

IMAGE_MODELS = Literal["z-image", "qwen-image-3"]

CANDIDATES: tuple[str, ...] = ("z-image", "qwen-image-3")
"""Priced alongside every generation so the choice is visible rather than
implied. Estimates are free, and both models were measured at ~80 seconds, so
the trade-off is purely price against quality — not price against speed."""


class _Params(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class GenerateImageParams(_Params):
    prompt: str = Field(
        min_length=3,
        max_length=800,
        description=(
            "What the image should show, in English or Russian. Be concrete about "
            "subject, setting and style. Longer than 800 characters is rejected "
            "before anything is charged."
        ),
    )
    aspect_ratio: ASPECT_RATIOS = "16:9"
    model: IMAGE_MODELS | None = Field(
        default=None,
        description=(
            "Which model to spend on. 'z-image' costs 1.2 RUB and is fine for a "
            "plain photographic scene. 'qwen-image-3' costs 7 RUB and is the one "
            "to pick when the image needs legible text in it or convincing "
            "photorealism. Both take about 80 seconds, so this is a price-versus-"
            "quality choice, not a speed one. Say which you chose and why before "
            "calling. Leave empty for the configured default."
        ),
    )


class EstimateParams(_Params):
    media_type: Literal["image", "video", "voice", "music"] = Field(
        description="What kind of generation to price."
    )
    prompt: str = Field(min_length=3, max_length=800)
    model: str | None = Field(
        default=None,
        description=(
            "Catalogue key. Leave empty for the default of that media type. "
            "Video keys are priced here but cannot be generated by any tool."
        ),
    )


def register(registry: ToolRegistry, client: VibemarketologClient) -> None:
    """Publish the generation tools. Call before ``registry.freeze()``."""

    async def generate_image(ctx: ToolContext, params: GenerateImageParams) -> ToolResult:
        model = params.model or client.settings.image_model

        # Free, and it is what makes the choice inspectable: the answer carries
        # what every candidate would have cost, not just what this one did.
        alternatives: dict[str, JsonValue] = {}
        for candidate in CANDIDATES:
            try:
                quote = await client.estimate(
                    {"type": "image", "model": candidate, "prompt": params.prompt}
                )
                alternatives[candidate] = quote.get("price_rub")
            except GenerationError:
                alternatives[candidate] = None

        body: dict[str, Any] = {
            "type": "image",
            "model": model,
            "prompt": params.prompt,
            "aspect_ratio": params.aspect_ratio,
        }
        try:
            generation_id = await client.start_generation(body)
            finished = await client.await_generation(
                generation_id, timeout_seconds=client.settings.image_timeout_seconds
            )
        except GenerationError as exc:
            return ToolResult.failed(
                ToolErrorCode.UPSTREAM_ERROR if exc.retryable else ToolErrorCode.INVALID_ARGUMENTS,
                str(exc),
                retryable=exc.retryable,
            )

        return ToolResult.ok(
            {
                "url": _first_url(finished),
                "model": model,
                "cost_rub": finished.get("cost"),
                "generation_id": generation_id,
                "alternatives_rub": alternatives,
            }
        )

    async def estimate_generation(ctx: ToolContext, params: EstimateParams) -> ToolResult:
        body: dict[str, Any] = {"type": params.media_type, "prompt": params.prompt}
        if params.model:
            body["model"] = params.model
        try:
            estimate = await client.estimate(body)
        except GenerationError as exc:
            return ToolResult.failed(ToolErrorCode.INVALID_ARGUMENTS, str(exc))

        # `reserve_rub` is the text-model field; everything else reports
        # `price_rub`. Reading both means one tool prices every media type.
        price = estimate.get("price_rub") or estimate.get("reserve_rub")
        daily = estimate.get("daily_spend") or {}
        return ToolResult.ok(
            {
                "media_type": params.media_type,
                "model": estimate.get("model"),
                "price_rub": price,
                "affordable": estimate.get("funds_ok"),
                "balance_now": (estimate.get("balance") or {}).get("current"),
                "balance_after": estimate.get("balance_after"),
                "daily_limit_rub": daily.get("limit"),
                "daily_spent_rub": daily.get("today"),
                "within_daily_limit": daily.get("within_limit"),
                "charged": False,
            }
        )

    registry.register(
        ToolSpec(
            name=f"{NAMESPACE}.generate_image",
            description=(
                "Generate one image from a text description and return its URL. "
                "This SPENDS MONEY from the account balance and cannot be undone, "
                "so say what you are about to make before calling it. Takes tens of "
                "seconds. For anything other than an image — video, voice, music — "
                "there is no generation tool; use estimate_generation to price it "
                "and tell the user the figure."
            ),
            params=GenerateImageParams,
            side_effect=SideEffect.WRITE,
            estimated_cost_usd=0.0,
            timeout_seconds=client.settings.image_timeout_seconds + 10.0,
        ),
        generate_image,
    )
    registry.register(
        ToolSpec(
            name=f"{NAMESPACE}.estimate_generation",
            description=(
                "Price a generation without producing it. FREE and charges nothing. "
                "Works for image, video, voice and music. Use it whenever someone "
                "asks what something would cost, and always before an expensive "
                "generation. Video can only be priced this way — nothing here can "
                "generate a clip."
            ),
            params=EstimateParams,
            side_effect=SideEffect.READ,
            timeout_seconds=20.0,
        ),
        estimate_generation,
    )


def _first_url(payload: dict[str, Any]) -> str | None:
    """Find the produced file, whichever shape the reply uses.

    The catalogue documents several conventions for handing a URL back; rather
    than guessing one, look through the ones that exist in order.
    """
    # display_url and result_url are signed and expire; file_url is stable.
    for key in ("result_url", "display_url", "file_url", "url", "image_url"):
        value = payload.get(key)
        if isinstance(value, str) and value:
            return value

    for key in ("urls", "result_urls", "files", "images"):
        value = payload.get(key)
        if isinstance(value, list) and value:
            first = value[0]
            if isinstance(first, str):
                return first
            if isinstance(first, dict):
                nested = first.get("url") or first.get("file_url")
                if isinstance(nested, str):
                    return nested

    result = payload.get("result") or payload.get("result_object")
    if isinstance(result, dict):
        return _first_url(result)
    return None
