"""Offline tests for the CRM adapter.

Every response here comes from ``demo_data/itmano_crm/demo-tenant.json``, which
the CRM generated by calling its own endpoints. Using that rather than
hand-written stubs means these tests fail when the real shape changes, instead of
passing against a fiction.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import httpx
import pytest
import respx
from pydantic import SecretStr, ValidationError

from conduit.adapters.itmano_crm import ItmanoCrmClient, ItmanoCrmSettings
from conduit.adapters.itmano_crm.client import ConfigurationError
from conduit.adapters.itmano_crm.contract import operation, operations
from conduit.adapters.itmano_crm.models import CreateLeadParams, LeadStage, ListLeadsParams
from conduit.adapters.itmano_crm.tools import agent_tool_operations, register
from conduit.core.tools import (
    SideEffect,
    ToolCall,
    ToolContext,
    ToolErrorCode,
    ToolRegistry,
    ToolStatus,
)

BASE = "https://crm.test"
API = f"{BASE}/api/agent/v1"

DEMO = json.loads(
    (
        Path(__file__).resolve().parent.parent
        / "conduit"
        / "demo_data"
        / "itmano_crm"
        / "demo-tenant.json"
    ).read_text(encoding="utf-8")
)

WHOAMI = {
    "tenant": {"id": "tenant-conduit-demo", "name": "Costa Verde Realty"},
    "scopes": ["read"],
    "api_version": "v1",
    "environment": "sbx",
    "token": {"expires_at": "2026-11-15T09:37:27.750Z"},
}


def error_body(code: str, message: str, retryable: bool = False) -> dict[str, Any]:
    return {"error": {"code": code, "message": message, "retryable": retryable}}


@pytest.fixture
def settings() -> ItmanoCrmSettings:
    return ItmanoCrmSettings(
        base_url=BASE,
        token=SecretStr("itmano_agent_sbx_test"),
        expected_tenant="tenant-conduit-demo",
        expected_environment="sbx",
    )


@pytest.fixture
async def crm(settings: ItmanoCrmSettings):
    async with ItmanoCrmClient(settings) as client:
        yield client


@pytest.fixture
def crm_registry(crm: ItmanoCrmClient) -> ToolRegistry:
    registry = ToolRegistry()
    register(registry, crm)
    return registry


class TestContract:
    def test_only_agent_marked_operations_become_tools(self) -> None:
        excluded = {op_id for op_id, op in operations().items() if not op.agent_tool}

        assert excluded == {"listContacts", "getContact"}
        assert len(agent_tool_operations()) == 11

    def test_timeouts_sit_above_the_server_deadline(self) -> None:
        for op in operations().values():
            assert op.timeout_seconds(15.0) > op.deadline_ms / 1000.0

    def test_the_ceiling_wins_over_a_generous_deadline(self) -> None:
        write = operation("createLead")

        assert write.deadline_ms == 8000
        assert write.timeout_seconds(ceiling=10.0) == 10.0

    def test_scopes_decide_the_side_effect(self, crm_registry: ToolRegistry) -> None:
        writes = {
            spec.name for spec in crm_registry.specs() if spec.side_effect is SideEffect.WRITE
        }

        assert writes == {
            "itmano_crm.create_lead",
            "itmano_crm.update_lead",
            "itmano_crm.create_note",
            "itmano_crm.draft_email",
        }


class TestRegistration:
    def test_every_agent_operation_gets_a_tool(self, crm_registry: ToolRegistry) -> None:
        assert len(crm_registry) == 11
        assert all(spec.namespace == "itmano_crm" for spec in crm_registry.specs())

    def test_contacts_are_not_offered_to_the_planner(self, crm_registry: ToolRegistry) -> None:
        names = {spec.name for spec in crm_registry.specs()}

        assert not any("contact" in name for name in names)

    def test_the_deal_amount_trap_is_stated_in_the_description(
        self, crm_registry: ToolRegistry
    ) -> None:
        """The planner sees descriptions and nothing else."""
        description = crm_registry.spec("itmano_crm.list_deals").description

        assert "always null" in description
        assert "lead_budget_amount" in description


class TestReadPaths:
    @respx.mock
    async def test_list_leads_passes_filters_through(self, crm_registry, ctx) -> None:
        route = respx.get(f"{API}/leads").mock(
            return_value=httpx.Response(200, json={"data": DEMO["leads"][:3], "next_cursor": None})
        )

        result = await crm_registry.invoke(
            ToolCall(
                id="c1",
                name="itmano_crm.list_leads",
                arguments={"stage": "cerrado", "limit": 3},
            ),
            ctx,
        )

        assert result.status is ToolStatus.OK
        assert route.calls.last.request.url.params["stage"] == "cerrado"
        assert route.calls.last.request.url.params["limit"] == "3"
        # Unset optional filters must not be sent at all.
        assert "owner" not in route.calls.last.request.url.params

    @respx.mock
    async def test_the_bearer_token_is_sent(self, crm_registry, ctx) -> None:
        route = respx.get(f"{API}/whoami").mock(return_value=httpx.Response(200, json=WHOAMI))

        await crm_registry.invoke(ToolCall(id="c1", name="itmano_crm.whoami"), ctx)

        assert route.calls.last.request.headers["authorization"] == "Bearer itmano_agent_sbx_test"

    @respx.mock
    async def test_get_lead_puts_the_id_in_the_path(self, crm_registry, ctx) -> None:
        lead = DEMO["leads"][0]
        route = respx.get(f"{API}/leads/{lead['id']}").mock(
            return_value=httpx.Response(200, json=lead)
        )

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.get_lead", arguments={"id": lead["id"]}),
            ctx,
        )

        assert result.status is ToolStatus.OK
        assert route.called

    @respx.mock
    async def test_deals_carry_a_null_amount_through_untouched(self, crm_registry, ctx) -> None:
        """If this ever stops being null the tool description is a lie."""
        respx.get(f"{API}/deals").mock(
            return_value=httpx.Response(200, json={"data": DEMO["deals"][:5], "next_cursor": None})
        )

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_deals", arguments={}), ctx
        )

        assert result.status is ToolStatus.OK
        assert isinstance(result.data, dict)
        rows = result.data["data"]
        assert isinstance(rows, list)
        assert rows
        for row in rows:
            assert isinstance(row, dict)
            assert row["amount"] is None


class TestErrorTranslation:
    @pytest.mark.parametrize(
        ("status", "code", "expected", "retryable"),
        [
            (404, "not_found", ToolErrorCode.NOT_FOUND, False),
            (403, "insufficient_scope", ToolErrorCode.UNAUTHORIZED, False),
            (400, "invalid_arguments", ToolErrorCode.INVALID_ARGUMENTS, False),
            (409, "idempotency_key_reuse", ToolErrorCode.INVALID_ARGUMENTS, False),
            (409, "idempotency_key_in_flight", ToolErrorCode.UPSTREAM_ERROR, True),
            (429, "rate_limited", ToolErrorCode.RATE_LIMITED, True),
            (504, "timeout", ToolErrorCode.TIMEOUT, True),
        ],
    )
    @respx.mock
    async def test_published_codes_map_to_the_taxonomy(
        self, crm_registry, ctx, status, code, expected, retryable
    ) -> None:
        respx.get(f"{API}/leads").mock(
            return_value=httpx.Response(status, json=error_body(code, "nope", retryable))
        )

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_leads", arguments={}), ctx
        )

        assert result.status is ToolStatus.FAILED
        assert result.error is not None
        assert result.error.code is expected
        assert result.error.retryable is retryable

    @respx.mock
    async def test_a_body_that_is_not_our_envelope_falls_back_to_the_status(
        self, crm_registry, ctx
    ) -> None:
        """What a challenge page or a proxy error actually looks like."""
        respx.get(f"{API}/leads").mock(
            return_value=httpx.Response(403, html="<title>Security Checkpoint</title>")
        )

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_leads", arguments={}), ctx
        )

        assert result.error is not None
        assert result.error.code is ToolErrorCode.UNAUTHORIZED

    @respx.mock
    async def test_an_unknown_code_does_not_invent_retryability(self, crm_registry, ctx) -> None:
        respx.get(f"{API}/leads").mock(
            return_value=httpx.Response(418, json=error_body("teapot", "contract drifted", True))
        )

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_leads", arguments={}), ctx
        )

        assert result.error is not None
        assert result.error.code is ToolErrorCode.UPSTREAM_ERROR
        assert result.error.retryable is False

    @respx.mock
    async def test_a_dead_network_becomes_a_result_not_an_exception(
        self, crm_registry, ctx
    ) -> None:
        respx.get(f"{API}/leads").mock(side_effect=httpx.ConnectError("no route to host"))

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_leads", arguments={}), ctx
        )

        assert result.status is ToolStatus.FAILED
        assert result.error is not None
        assert result.error.code is ToolErrorCode.UPSTREAM_ERROR
        assert result.error.retryable is True


class TestWritePaths:
    @respx.mock
    async def test_create_lead_forwards_the_idempotency_key(self, crm_registry, ctx) -> None:
        route = respx.post(f"{API}/leads").mock(
            return_value=httpx.Response(201, json={"id": "demo-lead-061"})
        )
        keyed = ToolContext(
            tenant_id=ctx.tenant_id,
            session_id=ctx.session_id,
            actor_id=ctx.actor_id,
            request_id=ctx.request_id,
            idempotency_key="turn-7",
        )

        result = await crm_registry.invoke(
            ToolCall(
                id="c1",
                name="itmano_crm.create_lead",
                arguments={
                    "first_name": "Prueba",
                    "last_name": "Humo",
                    "email": "prueba.humo@example.com",
                    "owner": "demo-agent-01",
                },
            ),
            keyed,
        )

        assert result.status is ToolStatus.OK
        request = route.calls.last.request
        assert request.headers["idempotency-key"] == "turn-7"
        assert json.loads(request.content)["language"] == "es"

    @respx.mock
    async def test_update_lead_keeps_the_id_out_of_the_body(self, crm_registry, ctx) -> None:
        route = respx.patch(f"{API}/leads/demo-lead-001").mock(
            return_value=httpx.Response(201, json={"id": "demo-lead-001", "stage": "en_proceso"})
        )

        result = await crm_registry.invoke(
            ToolCall(
                id="c1",
                name="itmano_crm.update_lead",
                arguments={"id": "demo-lead-001", "stage": "en_proceso"},
            ),
            ctx,
        )

        assert result.status is ToolStatus.OK
        body = json.loads(route.calls.last.request.content)
        assert body == {"stage": "en_proceso"}

    @respx.mock
    async def test_a_201_from_patch_is_treated_as_success(self, crm_registry, ctx) -> None:
        """The contract really does declare 201 here, not 200."""
        respx.patch(f"{API}/leads/demo-lead-001").mock(
            return_value=httpx.Response(201, json={"id": "demo-lead-001"})
        )

        result = await crm_registry.invoke(
            ToolCall(
                id="c1",
                name="itmano_crm.update_lead",
                arguments={"id": "demo-lead-001", "owner": "demo-agent-02"},
            ),
            ctx,
        )

        assert result.status is ToolStatus.OK


class TestArgumentValidation:
    def test_an_invented_stage_is_refused_before_any_request(self) -> None:
        with pytest.raises(ValidationError):
            ListLeadsParams(stage="won")  # type: ignore[arg-type]

    def test_the_contract_enum_is_what_we_accept(self) -> None:
        assert ListLeadsParams(stage=LeadStage.CERRADO).stage is LeadStage.CERRADO

    def test_creating_a_lead_without_an_owner_fails_locally(self) -> None:
        """The CRM has no unassigned state, so this must never reach the network."""
        with pytest.raises(ValidationError):
            CreateLeadParams(  # type: ignore[call-arg]
                first_name="Ana",
                email="ana@example.com",
            )

    def test_unknown_arguments_are_rejected(self) -> None:
        with pytest.raises(ValidationError):
            ListLeadsParams(tenant_id="tenant-otro")  # type: ignore[call-arg]

    @respx.mock
    async def test_an_over_large_limit_never_leaves_the_process(self, crm_registry, ctx) -> None:
        route = respx.get(f"{API}/leads").mock(return_value=httpx.Response(200, json={"data": []}))

        result = await crm_registry.invoke(
            ToolCall(id="c1", name="itmano_crm.list_leads", arguments={"limit": 500}), ctx
        )

        assert result.error is not None
        assert result.error.code is ToolErrorCode.INVALID_ARGUMENTS
        assert not route.called


class TestStartupAssertion:
    @respx.mock
    async def test_verify_accepts_the_expected_tenant(self, crm: ItmanoCrmClient) -> None:
        respx.get(f"{API}/whoami").mock(return_value=httpx.Response(200, json=WHOAMI))

        identity = await crm.verify()

        assert identity.tenant_id == "tenant-conduit-demo"
        assert identity.can_write is False

    @respx.mock
    async def test_verify_refuses_a_different_tenant(self, crm: ItmanoCrmClient) -> None:
        respx.get(f"{API}/whoami").mock(
            return_value=httpx.Response(
                200, json={**WHOAMI, "tenant": {"id": "tenant-not-ours", "name": "Someone Else"}}
            )
        )

        with pytest.raises(ConfigurationError, match="tenant-not-ours"):
            await crm.verify()

    @respx.mock
    async def test_verify_refuses_production(self, crm: ItmanoCrmClient) -> None:
        respx.get(f"{API}/whoami").mock(
            return_value=httpx.Response(200, json={**WHOAMI, "environment": "production"})
        )

        with pytest.raises(ConfigurationError, match="production"):
            await crm.verify()
